# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "AI Add-on for Home Assistant"
version: "1.2.0"
slug: "ai"
description: "AI Add-on for Home Assistant"
url: "https://x.com/m_pajew_ski"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
ingress: true
startup: services
ports:
  8099/tcp: 8099
