# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "AI Add-on"
description: "Chainlit in Home Assistant"
version: "1.3.0"
slug: "ai"
init: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8080/tcp: 8080
url: "https://github.com/pajew-ski/home-assistant-addons/tree/main/ai"
map:
  - share:rw
  - ssl
options:
  message: "sk-"
schema:
  message: "str?"
ingress: true
ingress_port: 8080
configuration:
  ssl:
    name: Enable SSL
    description: Enable usage of SSL on the webserver inside the add-on
network:
  8080/TCP: The webserver port (Not used for Ingress)
