# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: ai add-on
version: "1.3.0"
slug: ai
description: AI Add-on
url: "https://github.com/pajew-ski/home-assistant-addons/tree/main/ai"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "HAAI"
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-ai"
